version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  BeforeInstall:
#   - location: /usr/bin/ls
#     timeout: 300
#     runas: root
  AfterInstall:
    - location: bundle install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: bundle exec ruby app.rb
      timeout: 300
      runas: root

