version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/SlayTheReport
permissions:
  - object: /home/ubuntu/SlayTheReport
    pattern: "**"
    owner: ubuntu

hooks:
  BeforeInstall:
#   - location: /usr/bin/ls
#     timeout: 300
#     runas: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root

