version: '3'
services:
  dynamodb:
    build: docker/dynamodb-local
    ports:
      - 8000:8000

  sinatra:
    build: 
      context: .
      dockerfile: docker/DockerfileLocaldb
    volumes: 
      - .:/app
    environment:
      - DB_MODE=local
    ports:
      - 127.0.0.1:80:80
