version: '3'
services:
  sinatra:
    image: 947597759324.dkr.ecr.ap-northeast-1.amazonaws.com/slaythereport_mountless
    working_dir: /app
    environment:
      - DB_MODE=staging
    command: bash start.sh
    ports:
    - 0.0.0.0:80:80

