version: '3'
services:
  sinatra:
    build: .
    volumes:
      - ~/environment/SlayTheReport/app:/app
    working_dir: /app
    environment:
      - DB_MODE=standalone
    command: bash start_standalone.sh
    ports:
    - 127.0.0.1:8080:80

