version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000

  sinatra:
    build: .
    volumes: 
      - .:/app
    environment:
      - DB_MODE=local
    ports:
      - 127.0.0.1:80:80
