# frozen_string_literal: true

ruby '2.7.5'
source 'https://rubygems.org'
gem 'aws-sdk'
gem 'oauth'
gem 'rubocop', '~> 1.22', require: false
gem 'sinatra'
gem 'sinatra-contrib'
gem 'twitter'

group :test do
  gem 'rack-test'
  gem 'rspec'
end
