require 'json'

def img(key, size=200)
  map = {
    # events
    'neow' =>  'misc/neow.png',
    'shop' =>  'misc/shop.png',
    'campfire' =>  'misc/campfire.png',
    'chest' => 'misc/largeChest.png',
    # graphics
    'hp'   =>  'misc/hp.png',
    'gold' =>  'misc/gold.png',
    # random events
    'Liars Game' => 'events/liarsGame.jpg',
    # relics
    'Ancient Tea Set' => 'relics/tea_set.png',
    # Ironcrad cards
    "Bash"               =>  0,
    "Anger"              =>  0,
    "Armaments"          =>  0,
    "Body Slam"          =>  0,
    "Clash"              =>  0,
    "Cleave"             =>  0,
    "Clothesline"        =>  0,
    "Flex"               =>  0,
    "Havoc"              =>  0,
    "Headbutt"           =>  0,
    "Heavy Blade"        =>  0,
    "Iron Wave"          =>  0,
    "Perfected Strike"   =>  0,
    "Pommel Strike"      =>  0,
    "Shrug It Off"       =>  0,
    "Sword Boomerang"    =>  0,
    "Thunderclap"        =>  0,
    "True Grit"          =>  0,
    "Twin Strike"        =>  0,
    "Warcry"             =>  0,
    "Wild Strike"        =>  0,
    "Battle Trance"      =>  0,
    "Blood for Blood"    =>  0,
    "Bloodletting"       =>  0,
    "Burning Pact"       =>  0,
    "Carnage"            =>  0,
    "Combust"            =>  0,
    "Dark Embrace"       =>  0,
    "Disarm"             =>  0,
    "Dropkick"           =>  0,
    "Dual Wield"         =>  0,
    "Entrench"           =>  0,
    "Evolve"             =>  0,
    "Feel No Pain"       =>  0,
    "Fire Breathing"     =>  0,
    "Flame Barrier"      =>  0,
    "Ghostly Armor"      =>  0,
    "Hemokinesis"        =>  0,
    "Infernal Blade"     =>  0,
    "Inflame"            =>  0,
    "Intimidate"         =>  0,
    "Metallicize"        =>  0,
    "Power Through"      =>  0,
    "Pummel"             =>  0,
    "Rage"               =>  0,
    "Rampage"            =>  0,
    "Reckless Charge"    =>  0,
    "Rupture"            =>  0,
    "Searing Blow"       =>  0,
    "Second Wind"        =>  0,
    "Seeing Red"         =>  0,
    "Sentinel"           =>  0,
    "Sever Soul"         =>  0,
    "Shockwave"          =>  0,
    "Spot Weakness"      =>  0,
    "Uppercut"           =>  0,
    "Whirlwind"          =>  0,
    "Barricade"          =>  0,
    "Berserk"            =>  0,
    "Bludgeon"           =>  0,
    "Brutality"          =>  0,
    "Corruption"         =>  0,
    "Demon Form"         =>  0,
    "Double Tap"         =>  0,
    "Exhume"             =>  0,
    "Feed"               =>  0,
    "Fiend Fire"         =>  0,
    "Immolate"           =>  0,
    "Impervious"         =>  0,
    "Juggernaut"         =>  0,
    "Limit Break"        =>  0,
    "Offering"           =>  0,
    "Reaper"             =>  0,

  }
  if map.key?(key) then
    return "<img src='https://slaythereport-images.s3.ap-northeast-1.amazonaws.com/#{map[key]}' style='width:#{size}pt'></img>"
  else
    return "no-image: " + key
  end
end
